# -*- coding: utf-8 -*-
"""convert_numbers.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_oo9OgwiPetNm9HtAUcb9gcPZSjbSn9N
"""

#Google Drive Connection
from google.colab import drive
drive.mount('/content/drive')

filename ="/content/drive/MyDrive/Colab Notebooks/Pruebas de SW y Calidad/Problema 1/TC1.txt"

def read_numbers_from_file(filename):
   numbers = []
   with open(filename, 'r') as file:
    for line in file:
      try:
        numbers.append(int(line.strip()))
      except ValueError:
                print(f"Error: Invalid data '{line.strip()}' ignored.")
   return numbers

numbers = read_numbers_from_file(filename)

import time
start_time = time.time()

def to_binary(n):
    binary = ""
    if n == 0:
        return "0"
    while n > 0:
        binary = str(n % 2) + binary
        n //= 2
    return binary

def to_hexadecimal(n):
    hex_digits = "0123456789ABCDEF"
    hexadecimal = ""
    if n == 0:
        return "0"
    while n > 0:
        hexadecimal = hex_digits[n % 16] + hexadecimal
        n //= 16
    return hexadecimal

tiempo_t = time.time() - start_time

resultado = [
        f"{num} -> Binary: {to_binary(num)} ,Hexadecimal: {to_hexadecimal(num)}\n"
        for num in numbers
  ]
  resultado.append(f"Time Elapsed: {tiempo_t:.6f} seconds")

print(resultado)
print("Tiempo transcurrido:", (tiempo_t), "segundos.")

resultado_f = "\n".join(resultado)
with open("convertionResults.txt", "w") as output_file:
        output_file.write(resultado_f)

pip install pylint

!pylint "/content/drive/MyDrive/Colab Notebooks/Pruebas de SW y Calidad/Problema 2/convert_numbers.ipynb"